config/routes.rb
Rails.application.routes.draw do
  resources:schema
  resources:volumes do
    resources:v_ratings
    resources:vreviews
    resources:v_comments
  end
  resources:series do
    resources:s_ratings
    resources:sreviews
    resources:s_comments
  end
  
  resources:publisher
  resources:franchise
  resources:reviews do
    resources:issues
    resources:users
  end

  resources:issues do
    resources:i_ratings
    resources:i_comments
    resources:reviews
    collection do
      get:search
    end
  end
  resources:users do
    resources:u_comments
    resources:flists
  end
  
  resources:news do
      resources:m_comments
  end
  
  
  get 'users/:id/icomments' => 'users#icomments', :as => :user_icomments

  get 'sessions/new'
  get 'franchise/show'
  get 'static_pages/home'

  #delete  'issues/:id/i_comments/:id'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  get    '/logout',  to: 'sessions#destroy'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
end

app/models/flist.rb
class Flist < ApplicationRecord
  self.table_name = 'flist'
  belongs_to:user
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base
    self.table_name = 'Franchise'
    self.primary_key = :franchiseID
    has_many :series
    belongs_to :publisher
end

app/models/i_comment.rb
class IComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to:issue
    belongs_to:user
end

app/models/i_rating.rb
class IRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :issue
    def self.star(id)
        total = 0
        count = 0
        where(:issue_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
        end
        if(count > 0)
            total/count
        else
            count
        end
    end
    
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    self.table_name = 'Issue'
    self.primary_key = :issueID
  
    def self.search(search)
      search = search.downcase
      where("lower(issuename) Like ? OR lower(summary) Like ? OR lower(synopsis) Like ? OR lower(artist) Like ? OR lower(author) Like ? OR lower(editor) Like ?" , "%#{search}%" ,"%#{search}%","%#{search}%", "%#{search}%" ,"%#{search}%","%#{search}%")
    end
    has_many :IComments, dependent: :destroy
    has_many :IRatings, dependent: :destroy
    has_many :reviews, dependent: :destroy
    belongs_to :volume
end

app/models/m_comment.rb
class MComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :user
    belongs_to :news
end

app/models/news.rb
class News < ActiveRecord::Base
    self.table_name = 'New'
    self.primary_key = :newsId
    has_many :MComments
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
    self.table_name = 'Publisher'
    self.primary_key = :publisherID
    has_many :franchise
end

app/models/review.rb
class Review < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:issue
  belongs_to:user
end

app/models/s_comment.rb
class SComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :series
    belongs_to :user
end

app/models/s_rating.rb
class SRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :series
    def self.star(id)
    total = 0
    count = 0
    where(:series_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
    end
    if(count>0)
        total/count
    else
        count
    end
    end
    
end

app/models/series.rb
class Series < ActiveRecord::Base
    self.table_name = 'Series'
    self.primary_key = :seriesID
    has_many :sreviews, dependent: :destroy
    has_many :volume
    belongs_to :franchise
    has_many :SRatings, dependent: :destroy
    has_many :SComments, dependent: :destroy
end

app/models/sreview.rb
class Sreview < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:series
  belongs_to:user
end

app/models/u_comment.rb
class UComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :IComments, dependent: :destroy
    has_many :MComments, dependent: :destroy
    has_many :UComments, dependent: :destroy
    has_many :VComments, dependent: :destroy
    has_many :SComments, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :sreviews, dependent: :destroy
    has_many :vreviews, dependent: :destroy
    has_many :flists, dependent: :destroy
    has_many :IRatings, dependent: :destroy
    before_save { self.email = email.downcase }
    self.table_name = 'User'
    self.primary_key = :userID
    validates :displayName, presence: true,
    uniqueness: true
     VALID_EMAIL_REGEX = /\A[\w+-.]+@[a-z\d-]+(.[a-z\d-]+)*.[a-z]+\z/i
    validates :email, presence: true, 
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
end

app/models/v_comment.rb
class VComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :volume
    belongs_to :user
end

app/models/v_rating.rb
class VRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :volume
    def self.star(id)
    total = 0
    count = 0
    where(:volume_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
    end
    if(count > 0)
        total/count
    else
        count
    end
    end

end

app/models/volume.rb
class Volume < ActiveRecord::Base
    self.table_name = 'Volume'
    self.primary_key = :volumeID
    has_many :vreviews, dependent: :destroy
    has_many :VRatings, dependent: :destroy
    has_many :VComments, dependent: :destroy
    has_many :issues
    belongs_to :series
end

app/models/vreview.rb
class Vreview < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:volume
  belongs_to:user
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :editorpermission, only: [:new,:create,:edit,:update]
  def new
    @iss = Issue.new
  end
  def create
    @iss = Issue.new(issue_params)
    if @iss.save
      redirect_to @iss
    else
      render 'new'
    end
  end
  
  def edit
    @iss = Issue.find(params[:id])
  end
  def show
    @iss = Issue.find(params[:id])
    @rating = @iss.IRatings.star(params[:id])
    store_location
    @comm = @iss.IComments
  end
  def update
    @iss = Issue.find(params[:id])
    if @iss.update_attributes(issue_params)
      redirect_to @iss
    else
      render 'edit'
    end
  end
  
  def index
  @iss = Issue.all
  if params[:search]
    @iss = Issue.search(params[:search])
  else
    @iss = Issue.all
  end
  end

  private
  def issue_params
      params.require(:issue).permit(:issuename,:cover,:synopsis,:summary,:artist,:author,:editor,:characters,:tags,:volume_id)
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/views/issues/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-3">Edit Volume</h1>
    <%= form_for(@iss) do |f| %>
      <%= f.label :issuename, "Title" %>
      <%= f.text_field :issuename, class: 'form-control' %>
      
      <%= f.label :cover, "Cover URL" %>
      <%= f.text_field :cover, class: 'form-control' %>
      
      <%= f.label :synopsis, "Synopsis" %>
      <%= f.text_area :synopsis, class: 'form-control' %>
      
      <%= f.label :summary, "Summary" %>
      <%= f.text_area :summary, class: 'form-control' %>
      
      <%= f.label :artist, "Artist/s" %>
      <%= f.text_field :artist, class: 'form-control' %>
      
      <%= f.label :author, "Author/s" %>
      <%= f.text_field :author, class: 'form-control' %>
      
      <%= f.label :editor, "Editor/s" %>
      <%= f.text_field :editor, class: 'form-control' %>
      
      <%= f.label :characters, "Character/s" %>
      <%= f.text_field :characters, class: 'form-control' %>
      
      <%= f.label :tags, "tag/s" %>
      <%= f.text_field :tags, class: 'form-control' %>
      
      <%= f.label :volume_id, "Volume (if volume not shown please add volume first)" %>
      <%= f.select :volume_id, options_from_collection_for_select(Volume.all, :volumeID, :volumename) %>


      <%= f.submit "Edit issue", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<footer> 
<%=render 'layouts/footer' %>
</footer>
  </body>
<html lang="en">

app/views/issues/index.html.erb
<%= render 'layouts/front' %>


<% if @iss.blank? %>
  <h4>
      <div class = "container fixed-middle">
      There are no issues containing the term <%= params[:search] %>.
      </div>
</h4>

<% end %>

app/views/issues/new.html.erb
<%= render 'layouts/navbar' %>
 
  <div class="container">
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-3">Add Issue</h1>
    <%= form_for(@iss) do |f| %>
      <%= f.label :issuename, "Title" %>
      <%= f.text_field :issuename, class: 'form-control' %>
      
      <%= f.label :cover, "Cover URL" %>
      <%= f.text_field :cover, class: 'form-control' %>
      
      <%= f.label :synopsis, "Synopsis" %>
      <%= f.text_area :synopsis, class: 'form-control' %>
      
      <%= f.label :summary, "Summary" %>
      <%= f.text_area :summary, class: 'form-control' %>
      
      <%= f.label :artist, "Artist/s" %>
      <%= f.text_field :artist, class: 'form-control' %>
      
      <%= f.label :author, "Author/s" %>
      <%= f.text_field :author, class: 'form-control' %>
      
      <%= f.label :editor, "Editor/s" %>
      <%= f.text_field :editor, class: 'form-control' %>
      
      <%= f.label :characters, "Character/s" %>
      <%= f.text_field :characters, class: 'form-control' %>
      
      <%= f.label :tags, "tag/s" %>
      <%= f.text_field :tags, class: 'form-control' %>
      
      <%= f.label :volume_id, "Volume (if volume not shown please add volume first)" %>
      <%= f.select :volume_id, options_from_collection_for_select(Volume.all, :volumeID, :volumename) %>


      <%= f.submit "Add new issue", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<footer> 
<%=render 'layouts/footer' %>
</footer>
  </body>
<html lang="en">

app/views/issues/show.html.erb
<!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

<% provide(:title, @iss.issuename) %>

<%= render 'layouts/navbar' %>
<br>
<div class = container>
    <div class="row">
        <div class = "col-sm-4">
         <img src= "<%=@iss.cover%>" class="img-fluid" alt="Responsive image" >
        </div>
        <div class = "col-sm-8">
            <div class="shadow-lg p-4 mb-4 bg-white">
                <h1>
                    <%= @iss.issuename %> : <br>
                </h1>
                    <p>
                    <b> Author: </b> <%= @iss.author %> <br>
                    <b> Artist: </b> <%= @iss.artist %> <br>
                    <b> Editor: </b> <%= @iss.editor %> <br>
                    <b> Summary: </b> <%= @iss.summary %> <br> <br>
                    <a href="/volumes/<%= @iss.volume.volumeID %>" class="btn btn-primary">Volume: <%=@iss.volume.volumename%></a><br> <br>
                    <a href="/series/<%= @iss.volume.series.seriesID %>" class="btn btn-primary">Series: <%=@iss.volume.series.seriesname%></a><br><br>
                    <a href="/franchise/<%= @iss.volume.series.franchise.franchiseID %>" class="btn btn-primary">Franchise: <%=@iss.volume.series.franchise.franchisename%></a><br><br>
                    <a href="/publisher/<%= @iss.volume.series.franchise.publisher.publisherID %>" class="btn btn-primary">Publisher: <%=@iss.volume.series.franchise.publisher.publisherName%></a> <br><br>
                    <a href="/issues/<%=@iss.issueID%>/reviews/" class="btn btn-primary" style="background-color:green;"> List of Reviews...</a> <br><br>
                    <br>
                    <% if logged_in? && (current_user.permission.to_i > 0) %>
                    <%= link_to "Edit", edit_issue_path %>
                    <% end %>
                </p>
            </div>
        </div>
    </div>
</div>
<div class = container>
    <div class="row">
        <div class="shadow-lg p-4 mb-4 bg-white">
        <b>Spoiler Synopsis: </b> <br>
        <div id="spoiler" style="display:none"> 
        <%= @iss.synopsis%>
        </div> 
        <button title="Show Spoilers" type="button" onclick="if(document.getElementById('spoiler') .style.display=='none') {document.getElementById('spoiler') .style.display=''}else{document.getElementById('spoiler') .style.display='none'}">Hide Spoilers</button>
        </div>
    </div>
</div>

<div class = container>
    <div class = "row">
    <p>
    Characters: <%= @iss.characters %> <br>
    </p>
    </div>
</div>
<%= render 'ratings/iform' %>
<%#= render 'reviews/iform' %>
<%= render 'comments/form' %>
<%= render 'layouts/issueComments' %>
</body>
<%= render 'layouts/footer'%>