config/routes.rb
Rails.application.routes.draw do
  resources:schema
  resources:volumes do
    resources:v_ratings
    resources:vreviews
    resources:v_comments
  end
  resources:series do
    resources:s_ratings
    resources:sreviews
    resources:s_comments
  end
  
  resources:publisher
  resources:franchise
  resources:reviews do
    resources:issues
    resources:users
  end

  resources:issues do
    resources:i_ratings
    resources:i_comments
    resources:reviews
    collection do
      get:search
    end
  end
  resources:users do
    resources:u_comments
    resources:flists
  end
  
  resources:news do
      resources:m_comments
  end
  
  
  get 'users/:id/icomments' => 'users#icomments', :as => :user_icomments

  get 'sessions/new'
  get 'franchise/show'
  get 'static_pages/home'

  #delete  'issues/:id/i_comments/:id'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  get    '/logout',  to: 'sessions#destroy'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
end

app/models/flist.rb
class Flist < ApplicationRecord
  self.table_name = 'flist'
  belongs_to:user
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base
    self.table_name = 'Franchise'
    self.primary_key = :franchiseID
    has_many :series
    belongs_to :publisher
end

app/models/i_comment.rb
class IComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to:issue
    belongs_to:user
end

app/models/i_rating.rb
class IRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :issue
    def self.star(id)
        total = 0
        count = 0
        where(:issue_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
        end
        if(count > 0)
            total/count
        else
            count
        end
    end
    
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    self.table_name = 'Issue'
    self.primary_key = :issueID
  
    def self.search(search)
      search = search.downcase
      where("lower(issuename) Like ? OR lower(summary) Like ? OR lower(synopsis) Like ? OR lower(artist) Like ? OR lower(author) Like ? OR lower(editor) Like ?" , "%#{search}%" ,"%#{search}%","%#{search}%", "%#{search}%" ,"%#{search}%","%#{search}%")
    end
    has_many :IComments, dependent: :destroy
    has_many :IRatings, dependent: :destroy
    has_many :reviews, dependent: :destroy
    belongs_to :volume
end

app/models/m_comment.rb
class MComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :user
    belongs_to :news
end

app/models/news.rb
class News < ActiveRecord::Base
    self.table_name = 'New'
    self.primary_key = :newsId
    has_many :MComments
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
    self.table_name = 'Publisher'
    self.primary_key = :publisherID
    has_many :franchise
end

app/models/review.rb
class Review < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:issue
  belongs_to:user
end

app/models/s_comment.rb
class SComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :series
    belongs_to :user
end

app/models/s_rating.rb
class SRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :series
    def self.star(id)
    total = 0
    count = 0
    where(:series_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
    end
    if(count>0)
        total/count
    else
        count
    end
    end
    
end

app/models/series.rb
class Series < ActiveRecord::Base
    self.table_name = 'Series'
    self.primary_key = :seriesID
    has_many :sreviews, dependent: :destroy
    has_many :volume
    belongs_to :franchise
    has_many :SRatings, dependent: :destroy
    has_many :SComments, dependent: :destroy
end

app/models/sreview.rb
class Sreview < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:series
  belongs_to:user
end

app/models/u_comment.rb
class UComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :IComments, dependent: :destroy
    has_many :MComments, dependent: :destroy
    has_many :UComments, dependent: :destroy
    has_many :VComments, dependent: :destroy
    has_many :SComments, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :sreviews, dependent: :destroy
    has_many :vreviews, dependent: :destroy
    has_many :flists, dependent: :destroy
    has_many :IRatings, dependent: :destroy
    before_save { self.email = email.downcase }
    self.table_name = 'User'
    self.primary_key = :userID
    validates :displayName, presence: true,
    uniqueness: true
     VALID_EMAIL_REGEX = /\A[\w+-.]+@[a-z\d-]+(.[a-z\d-]+)*.[a-z]+\z/i
    validates :email, presence: true, 
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
end

app/models/v_comment.rb
class VComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :volume
    belongs_to :user
end

app/models/v_rating.rb
class VRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :volume
    def self.star(id)
    total = 0
    count = 0
    where(:volume_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
    end
    if(count > 0)
        total/count
    else
        count
    end
    end

end

app/models/volume.rb
class Volume < ActiveRecord::Base
    self.table_name = 'Volume'
    self.primary_key = :volumeID
    has_many :vreviews, dependent: :destroy
    has_many :VRatings, dependent: :destroy
    has_many :VComments, dependent: :destroy
    has_many :issues
    belongs_to :series
end

app/models/vreview.rb
class Vreview < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:volume
  belongs_to:user
end

app/controllers/m_comments_controller.rb
class MCommentsController < ApplicationController
  before_action :get_news_and_comment, only: [:destroy, :edit, :update, :is_owner]
  before_action :is_owner, only: [:edit, :update]
  before_action :can_delete, only: [:destroy]
  def create
    @news = News.find(params[:news_id])
    @comm = News.find(@news.newsId).MComments.new(comment_params)
    @comm.user_id = current_user.userID
    if @comm.save
      redirect_to @news
    else
    end
  end
  def edit
  end
  def update
    if @comm.update_attributes(comment_params)
      redirect_to @news
    end
  end
  def destroy
    @comm.destroy
    redirect_to @news
  end
  private
  def comment_params
    params.require(:m_comment).permit(:body, :user_id)
  end
  def get_news_and_comment
    @news = News.find(params[:news_id])
    @comm = News.find(@news.newsId).MComments.find(params[:id])
  end
  def is_owner
    unless current_user.id == @comm.user_id
    redirect_to @new
    end
  end
end

app/helpers/m_comments_helper.rb
module MCommentsHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/views/m_comments/_comment.html.erb
   <% provide(:title,  @newpage.newsId) %>
  <% provide(:title, @iss.display) %>
    <div class = "container">
      <div class = "row">
        <div id: "comments">
          <div class="col-sm-12">
            <% @newpage.MComments.order(created_at: :desc).each do |mComments| %>
            
                  <p>
                    <img src = <%=mComments.user.profilePic%> width="80" height = "80" alt"">  <%=mComments.user.displayName%>
                  </p>
            <% if mComments.user.permission.to_i == 2%>
              <p style="color:red;">
                Admin  
              <img class = "mx-auto rounded-circle" src=<%= asset_path '/crown_bronze.png' %>>
              </p>
            <%end%>
            <% if mComments.user.permission.to_i == 1%>
             <p style ="color:green;">
               Editor
               <img class = "mx-auto rounded-circle" src=<%= asset_path '/wrench_orange.png' %>>
             </p>
             <%end%>
            <p>  Date: <%=mComments.date%>
            <% if logged_in? && (@current_user.userID == mComments.user_id || @current_user.permission.to_i > 1) %>
                <button>
                <%= button_to "Delete", [mComments.news, mComments], method: :delete %>
                </button>
                <button>
                <%= link_to "Edit", edit_news_m_comment_path(mComments.news, mComments) %>
                </button>
            <% end %>
            <br />
            </p>
            <p id = "comments"> <%=mComments.body%></p>
            
            <% end %>
          </div>
        </div>
      </div>
    </div>

app/views/m_comments/_form.html.erb
<%= render 'layouts/navbar'%>
<div class=container style="">
<% if logged_in? %>

        <%= form_for ([@newpage,@newpage.MComments.build]) do |f| %>
          <%= render 'shared/error_messages' %>

          <%= f.label :body, "Message" %>
          <%= f.text_area :body %>


          <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        <% end %>
      <% end %>
      </div>

app/views/m_comments/edit.html.erb
<%= render 'layouts/navbar'%>
<div class=container style="padding-top: 10%;">
      <% if logged_in? %>
      
        <%= form_for ([@news, @comm]) do |f| %>
          <%= render 'shared/error_messages' %>

          <%= f.label :body, "Comment" %>
          <%= f.text_area :body %>
          

          <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
        <% end %>
      <% end %>
</div>