config/routes.rb
Rails.application.routes.draw do
  resources:schema
  resources:volumes do
    resources:v_ratings
    resources:vreviews
    resources:v_comments
  end
  resources:series do
    resources:s_ratings
    resources:sreviews
    resources:s_comments
  end
  
  resources:publisher
  resources:franchise
  resources:reviews do
    resources:issues
    resources:users
  end

  resources:issues do
    resources:i_ratings
    resources:i_comments
    resources:reviews
    collection do
      get:search
    end
  end
  resources:users do
    resources:u_comments
    resources:flists
  end
  
  resources:news do
      resources:m_comments
  end
  
  
  get 'users/:id/icomments' => 'users#icomments', :as => :user_icomments

  get 'sessions/new'
  get 'franchise/show'
  get 'static_pages/home'

  #delete  'issues/:id/i_comments/:id'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  get    '/logout',  to: 'sessions#destroy'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
end

app/models/flist.rb
class Flist < ApplicationRecord
  self.table_name = 'flist'
  belongs_to:user
end

app/models/franchise.rb
class Franchise < ActiveRecord::Base
    self.table_name = 'Franchise'
    self.primary_key = :franchiseID
    has_many :series
    belongs_to :publisher
end

app/models/i_comment.rb
class IComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to:issue
    belongs_to:user
end

app/models/i_rating.rb
class IRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :issue
    def self.star(id)
        total = 0
        count = 0
        where(:issue_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
        end
        if(count > 0)
            total/count
        else
            count
        end
    end
    
end

app/models/issue.rb
class Issue < ActiveRecord::Base
    self.table_name = 'Issue'
    self.primary_key = :issueID
  
    def self.search(search)
      search = search.downcase
      where("lower(issuename) Like ? OR lower(summary) Like ? OR lower(synopsis) Like ? OR lower(artist) Like ? OR lower(author) Like ? OR lower(editor) Like ?" , "%#{search}%" ,"%#{search}%","%#{search}%", "%#{search}%" ,"%#{search}%","%#{search}%")
    end
    has_many :IComments, dependent: :destroy
    has_many :IRatings, dependent: :destroy
    has_many :reviews, dependent: :destroy
    belongs_to :volume
end

app/models/m_comment.rb
class MComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :user
    belongs_to :news
end

app/models/news.rb
class News < ActiveRecord::Base
    self.table_name = 'New'
    self.primary_key = :newsId
    has_many :MComments
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
    self.table_name = 'Publisher'
    self.primary_key = :publisherID
    has_many :franchise
end

app/models/review.rb
class Review < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:issue
  belongs_to:user
end

app/models/s_comment.rb
class SComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :series
    belongs_to :user
end

app/models/s_rating.rb
class SRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :series
    def self.star(id)
    total = 0
    count = 0
    where(:series_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
    end
    if(count>0)
        total/count
    else
        count
    end
    end
    
end

app/models/series.rb
class Series < ActiveRecord::Base
    self.table_name = 'Series'
    self.primary_key = :seriesID
    has_many :sreviews, dependent: :destroy
    has_many :volume
    belongs_to :franchise
    has_many :SRatings, dependent: :destroy
    has_many :SComments, dependent: :destroy
end

app/models/sreview.rb
class Sreview < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:series
  belongs_to:user
end

app/models/u_comment.rb
class UComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :IComments, dependent: :destroy
    has_many :MComments, dependent: :destroy
    has_many :UComments, dependent: :destroy
    has_many :VComments, dependent: :destroy
    has_many :SComments, dependent: :destroy
    has_many :reviews, dependent: :destroy
    has_many :sreviews, dependent: :destroy
    has_many :vreviews, dependent: :destroy
    has_many :flists, dependent: :destroy
    has_many :IRatings, dependent: :destroy
    before_save { self.email = email.downcase }
    self.table_name = 'User'
    self.primary_key = :userID
    validates :displayName, presence: true,
    uniqueness: true
     VALID_EMAIL_REGEX = /\A[\w+-.]+@[a-z\d-]+(.[a-z\d-]+)*.[a-z]+\z/i
    validates :email, presence: true, 
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
    end
end

app/models/v_comment.rb
class VComment < ActiveRecord::Base
    self.table_name = 'comments'
    self.primary_key = :commentId
    belongs_to :volume
    belongs_to :user
end

app/models/v_rating.rb
class VRating < ActiveRecord::Base
    self.table_name = 'rating'
    self.primary_key = :ratingID
    belongs_to :user
    belongs_to :volume
    def self.star(id)
    total = 0
    count = 0
    where(:volume_id => id).each do |rate|
        total += rate.rating.to_i
        count += 1
    end
    if(count > 0)
        total/count
    else
        count
    end
    end

end

app/models/volume.rb
class Volume < ActiveRecord::Base
    self.table_name = 'Volume'
    self.primary_key = :volumeID
    has_many :vreviews, dependent: :destroy
    has_many :VRatings, dependent: :destroy
    has_many :VComments, dependent: :destroy
    has_many :issues
    belongs_to :series
end

app/models/vreview.rb
class Vreview < ApplicationRecord
  self.table_name = 'Review'
  self.primary_key = :reviewid
  belongs_to:volume
  belongs_to:user
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :editorpermission, only: [:new,:create,:edit,:update]
  def new
    @ser = Series.new
  end
  def create
    @ser = Series.new(series_params)
    if @ser.save
      redirect_to @ser
    else
      render 'new'
    end
  end
  
  def edit
    @ser = Series.find(params[:id])
  end
  def update
    @ser = Series.find(params[:id])
    if @ser.update_attributes(series_params)
      redirect_to @ser
    else
      render 'edit'
    end
  end
  def show
    @ser = Series.find(params[:id])
    @rating = @ser.SRatings.star(params[:id])
    @comm = @ser.SComments
    store_location
  end
  private
  def series_params
     params.require(:series).permit(:seriesname,:picture,:franchise_id)
  end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/edit.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-3">Edit Series</h1>
    <%= form_for(@ser) do |f| %>
      <%= f.label :seriesname, "Series Title" %>
      <%= f.text_field :seriesname, class: 'form-control' %>
      
      <%= f.label :picture, "Cover URL" %>
      <%= f.text_field :picture, class: 'form-control' %>
      
      <%= f.label :franchise_id, "Franchise (if franchise not shown please add volume first)" %>
      <%= f.select :franchise_id, options_from_collection_for_select(Franchise.all, :franchiseID, :franchisename) %>


      <%= f.submit "Edit series", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<footer> 
<%=render 'layouts/footer' %>
</footer>
  </body>
<html lang="en">

app/views/series/new.html.erb
<%= render 'layouts/navbar' %>
<div class="container">
  <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="display-3">Add Series</h1>
    <%= form_for(@ser) do |f| %>
      <%= f.label :seriesname, "Series Title" %>
      <%= f.text_field :seriesname, class: 'form-control' %>
      
      <%= f.label :picture, "Cover URL" %>
      <%= f.text_field :picture, class: 'form-control' %>
      
      <%= f.label :franchise_id, "Franchise (if franchise not shown please add volume first)" %>
      <%= f.select :franchise_id, options_from_collection_for_select(Franchise.all, :franchiseID, :franchisename) %>


      <%= f.submit "Add new series", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<footer> 
<%=render 'layouts/footer' %>
</footer>
  </body>
<html lang="en">

app/views/series/show.html.erb
<% provide(:title, @ser.seriesname) %>

<%= render 'layouts/navbar' %>

<!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

<br>
<div class = container>
    <div class="row">
        <div class = "col-sm-4">
         <img src= "<%=@ser.picture%>" class="img-fluid" alt="Responsive image" >
        </div>
        <div class = "col-sm-8">
            <div class="shadow-lg p-4 mb-4 bg-white">
                <h1>
                    <%= @ser.seriesname %> : <br>
                </h1>
                    <p>
                    <a href="/franchise/<%= @ser.franchise.franchiseID %>" class="btn btn-primary">Franchise:<%=@ser.franchise.franchisename%></a><br><br>
                    <a href="/publisher/<%= @ser.franchise.publisher.publisherID %>" class="btn btn-primary">Publisher:<%=@ser.franchise.publisher.publisherName%></a><br><br>
                    <% @ser.volume.reorder('volumename').each do |volume| %>
                        <a href="/volumes/<%= volume.volumeID %>" class="btn btn-primary">Volume:<%=volume.volumename%></a>
                    <% end %>
                    <br><br>
                    <a href="/series/<%=@ser.seriesID%>/sreviews/" class="btn btn-primary" style="background-color:green;"> List of Reviews...</a> <br><br>
                    <% if logged_in? && (current_user.permission > 0) %>
                    <a><%= link_to "Edit",edit_series_path %></a>
                    <% end %>
                    </p>
            </div>
        </div>
    </div>
</div>
  <%= render 'ratings/sform' %>
  <%= render 'reviews/sform' %>
  <%= render 's_comments/form' %>
  <%= render 's_comments/comment' %>
</div>


</body>
<%= render 'layouts/footer'%>